"""add user settings

Revision ID: ed0ca5adb5d0
Revises: 1853a3d3e3f4
Create Date: 2026-09-21 20:54:04.748846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0ca5adb5d0'
down_revision: Union[str, Sequence[str], None] = '1853a3d3e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_enabled', sa.Boolean(), nullable=False),
    sa.Column('show_interests', sa.Boolean(), nullable=False),
    sa.Column('private_profile', sa.Boolean(), nullable=False),
    sa.Column('new_matches_notifications', sa.Boolean(), nullable=False),
    sa.Column('message_notifications', sa.Boolean(), nullable=False),
    sa.Column('activity_updates_notifications', sa.Boolean(), nullable=False),
    sa.Column('nearby_activities_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
